name: Build and Publish

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip   
          #pip install -r requirements.txt
          # Additional setup steps as needed

      - name: Build application
        run: |
            python setup.py sdist bdist_wheel  
          # Commands to build your application
          # For example, compiling code or bundling packages

      - name: Publish to CodeArtifact
        env:
          AWS_REGION: ap-south-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REPOSITORY_NAME: tcp-simulator
          PACKAGE_NAME: tcp-server-client
          PACKAGE_VERSION: 1.1.1
        run: |
          aws codeartifact login --tool pip --repository poc --domain questpoc --domain-owner 851725253190 --region ap-south-1
          aws codeartifact push-package-version --repository $REPOSITORY_NAME  --package tcp-server-client --version 1.1.1
