name: Build and Publish

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      #   pip install -r requirements.txt

      #- name: Run tests (if applicable)
      #  run: |
      #   pytest

      # - name: Package application
      # run: |
      #    python setup.py sdist bdist_wheel

      - name: Publish to CodeArtifact
        run: |
     
          aws codeartifact login --tool pip --repository poc --domain questpoc --domain-owner 851725253190 --region ap-south-1
          python -m twine upload --repository poc dist/*
