name: Build and Publish

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      #   pip install -r requirements.txt

      #- name: Run tests (if applicable)
      #  run: |
      #   pytest

      # - name: Package application
      # run: |
      #    python setup.py sdist bdist_wheel
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1 
        with: 
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      #- name: Get CodeArtifact Token
      #  id: codeartifact-token
      #  run: |
      #  export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain questpoc --domain-owner 851725253190 --query authorizationtoken --output text)
      #   echo "::set-output name=token::$CODEARTIFACT_AUTH_TOKEN
      - name: Login to AWS CodeArtifact
        run: aws codeartifact login --tool pip --domain questpoc --domain-owner 851725253190 --repository poc --region ap-south-1
 
      - name: Build and publish package 
        run: | 
           python setup.py sdist bdist_wheel 
           python -m pip upload --repository poc dist/*
       # env: 
       #  TWINE_USERNAME: __token__ 
       #  TWINE_PASSWORD: ${{ steps.codeartifact-token.outputs.token }}

